title: Markdoc
description: A literate programming package for Stata which develops dynamic documents, slides, and help files in various formats
google_analytics: 
show_downloads: true
theme: jekyll-theme-cayman

gems:
  - jekyll-mentions
